version: '3.5'
services:
  app:
    build: .
    environment:
      - DD_ENV
      - DD_TRACE_DEBUG
      - DD_TRACE_ENABLED
      - DD_LOGS_INJECTION=true
      - DD_AGENT_HOST=agent
    labels:
      com.datadoghq.ad.logs: '[{"source": "docker", "service": "user"}]'
  agent:
    image: datadog/agent:latest
    environment:
      - DD_ENV
      - DD_TAGS="env:${DD_ENV}"
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_APM_ENABLED=true
      - DD_APM_ANALYZED_SPANS=api-gateway|express.request=1,auth|express.request=1,user|express.request=1
      - DD_BIND_HOST=0.0.0.0
      - DD_LOGS_ENABLED=true
      - DD_API_KEY
      - DD_DD_URL
      - DD_APM_DD_URL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro