name: CI

description: Shared action to install dependencies

runs:
  using: composite

  steps:
    - name: Read .nvmrc
      id: nvm
      run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
      with:
        node-version-file: ".nvmrc"
        cache: "yarn"

    # Whenever on a changeset versioning PR
    # Then installing can not fail with lockfile changes
    # Because the package.json for integration test changes.

    - name: Install
      run: yarn install --immutable
      shell: bash
