export const HEADERS_CONTENT_TYPES = ['application/json', 'application/graphql']
export const DEFAULT_HEADERS = [
  'content-type',
  'access-control-allow-origin',
  'access-control-allow-headers',
  'access-control-allow-methods',
  'access-control-expose-headers',
  'access-control-max-ag',
  'x-correlation-id',
  'server-timing',
  'date',
  'server',
  'transfer-encoding',
  'access-control-max-age',
  'content-encoding',
  'x-envoy-upstream-service-time',
  'via',
  'alt-svc',
  'connection',
]
